[package]
name = "ExeViewer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.20", features = ["derive"] }
elf = "0.7.4"
iced-x86 = "1.21.0"
ratatui = "0.28.1"
strum = { version = "0.26", features = ["derive"] }

[profile.release]
lto = true